import { createHash, randomInt } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const alphabet = "23456789ABCDEFGHJKMNPQRSTUVWXYZ";
const tokenLength = 12;
const requestedCount = Number.parseInt(process.argv[2] || "200", 10);
const baseUrl = (process.env.NFC_BASE_URL || "https://justbaila.com/tap").replace(/\/$/, "");
const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectDirectory = path.resolve(scriptDirectory, "..");
const exportsDirectory = path.join(projectDirectory, "exports");
const seedsDirectory = path.join(projectDirectory, "worker", "seeds");

if (!Number.isInteger(requestedCount) || requestedCount < 1 || requestedCount > 10000) {
  throw new Error("Card count must be an integer between 1 and 10,000.");
}

await mkdir(exportsDirectory, { recursive: true });
await mkdir(seedsDirectory, { recursive: true });

const existingCards = await loadExistingCards(exportsDirectory);
const existingIds = new Set(existingCards.map((card) => card.cardId));
const highestCardNumber = existingCards.reduce(
  (highest, card) => Math.max(highest, Number.parseInt(card.cardNumber, 10) || 0),
  0
);

const cards = [];
for (let offset = 1; offset <= requestedCount; offset += 1) {
  let cardId;
  do {
    cardId = createCardId();
  } while (existingIds.has(cardId));

  existingIds.add(cardId);
  const inventoryNumber = highestCardNumber + offset;
  cards.push({
    cardNumber: String(inventoryNumber).padStart(3, "0"),
    cardId,
    nfcUrl: `${baseUrl}?id=${cardId}`,
    cardHash: sha256(cardId)
  });
}

const firstNumber = cards[0].cardNumber;
const lastNumber = cards.at(-1).cardNumber;
const batchName = `${firstNumber}-${lastNumber}`;
const csvPath = path.join(exportsDirectory, `nfc-cards-${batchName}.csv`);
const sqlPath = path.join(seedsDirectory, `cards-${batchName}.sql`);

const csv = [
  "card_number,card_id,nfc_url",
  ...cards.map((card) => `${card.cardNumber},${card.cardId},${card.nfcUrl}`)
].join("\n");

const sql = [
  "-- Generated by scripts/generate-cards.mjs. Raw card IDs remain only in the ignored CSV export.",
  ...cards.flatMap((card) => [
    `INSERT INTO cards (card_number, card_hash) VALUES ('${card.cardNumber}', '${card.cardHash}');`,
    `INSERT INTO passports (card_id) SELECT id FROM cards WHERE card_number = '${card.cardNumber}';`
  ]),
  ""
].join("\n");

await writeFile(csvPath, `${csv}\n`, { flag: "wx", mode: 0o600 });
await writeFile(sqlPath, sql, { flag: "wx" });

console.log(`Generated ${cards.length} unique cards.`);
console.log(`CSV: ${csvPath}`);
console.log(`D1 seed: ${sqlPath}`);

function createCardId() {
  return Array.from({ length: tokenLength }, () => alphabet[randomInt(alphabet.length)]).join("");
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

async function loadExistingCards(directory) {
  const files = (await readdir(directory)).filter((file) => file.endsWith(".csv"));
  const cards = [];

  for (const file of files) {
    const contents = await readFile(path.join(directory, file), "utf8");
    const lines = contents.trim().split(/\r?\n/).slice(1);
    for (const line of lines) {
      if (!line) continue;
      const [cardNumber, cardId] = line.split(",");
      if (cardNumber && cardId) cards.push({ cardNumber, cardId });
    }
  }

  return cards;
}
